name: Static Linting Only

on: [push]

jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Flake8 Lint
        uses: py-actions/flake8@v2
        with:
          ignore: "W191,E501,E128,E124,E126,E127"

  Type-Check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: mypy check
        run: |
          pip install mypy types-requests pandas-stubs typing_extensions
          mypy -p BunnyHop
